<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Promise</title>
</head>
<body>

<script>

    // //promise
    // let promise = new Promise((resolve,reject) =>{
    //     resolve(11111)    //条用resolve,reject 可以查看 页面console返回
    // })
    // promise.then(response => {
    //     console.log('成功')
    //     console.log(response) //可以输出resolve(111)里面值
    // }).catch(error => {
    //     console.log('失败')
    //     console.log(error)
    // })


    //链式
    function promise1(status){
        return new Promise((resolve,reject) =>{
            if(status){
                console.log('第一个promise成功');
                resolve('第一个promise成功返回数据成功')
            }
            if(!status){
                console.log('第一个promise失败')
                reject('第一个promise返回数据失败')
            }
        })
    }


       function promise2(status){
        return new Promise((resolve,reject) =>{
            if(status){
                console.log('第2个promise成功');
                resolve('第2个promise成功返回数据成功')
            }
            if(!status){
                console.log('第2个promise失败')
                reject('第2个promise返回数据失败')
            }
        })
    }


    function promise3(status){
        return new Promise((resolve,reject) =>{
            if(status){
                console.log('第3个promise成功');
                resolve('第3个promise成功返回数据成功')
            }
            if(!status){
                console.log('第3个promise失败')
                reject('第3个promise返回数据失败')
            }
        })
    }


        function promise4(status){
        return new Promise((resolve,reject) =>{
            if(status){
                console.log('第4个promise成功');
                resolve('第4个promise成功返回数据成功')
            }
            if(!status){
                console.log('第4个promise失败')
                reject('第4个promise返回数据失败')
            }
        })
    }


    //
    // promise1(true).then(response =>{
    //     console.log(response)   //这行也输出，调用了 resolve('第一个promise成功返回数据成功') //axios返回参数，判断是否执行第2个promise
    //     return promise2(true) //带上return返回promise2里面的参数数值
    // }).then(response =>{
    //     console.log(response)
    //     return promise4(true)
    // }).then(response=>{
    //     console.log(response)
    // }).catch(error =>{
    //     console.log(error)

    // //all方法庶族内有promise必须全部成功(全部返回resolve)，才会执行then回调，只要有一个不成功（返回reject）就会只从catch
    // Promise.all([promise1(true),promise2(false),promise3(true)]).then(response =>{
    //     console.log('全部调用成功');
    // }).catch(error =>{
    //     console.log('有些可能失败了');
    // })

    //race数组，当执行遇到返回resolve（成功）会一直执行链式，第一个决定返回结果，首成功提示全部成功，首失败提示失败
    Promise.race([promise1(true),promise2(false),promise3(false)]).then(response =>{
        console.log('全部调用成功');
    }).catch(error =>{
        console.log('有些可能失败了');
    })





</script>

</body>
</html>